# Generated by Django 3.2 on 2021-12-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('actual_entry_time', models.TimeField(null=True)),
                ('number_plate', models.CharField(max_length=50)),
                ('choice_category', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
